version: '3'
services:
  postgresql:
    image: postgres:latest
    hostname: postgresql
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4:latest
    hostname: pgadmin-postgresql
    ports:
      - 9080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=username@emailprovider.com
      - PGADMIN_DEFAULT_PASSWORD=password

   